default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: root
  host: localhost


development:
  <<: *default
  database: todo_api_dev

test:
  <<: *default
  database: todo_api_test

production:
  <<: *default
  database: Todo-Api_production
  username: Todo-Api
  password: <%= ENV['TODO-API_DATABASE_PASSWORD'] %>
